ins/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from .import views as views

app_name='login'

urlpatterns = [
     url(r'^$',views.insert),
     url(r'register/$',views.register),
    #url(r'^logout/$', auth_views.logout,name='logout'),
    #rl(r'^logg/',include('loginex.urls')),
    #url(r'^log/',include(loginex.urs))
]

login/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views


#from .import loginex
app_name='home1'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('loginex.urls'))
    #url(r'^login/base/$',VIEWS.index)
]

loginex/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from .import views as views
from django.contrib.auth import views as auth_views

app_name='login'

'''urlpatterns = [
    url(r'^login/', auth_views.login, {'template_name': 'index.html'},name='login'),
    url(r'register/$',views.register, name='register'),
    url(r'password_reset/$', auth_views.password_reset, name='password_reset'),
    #url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password_reset/$', auth_views.password_reset, {'post_reset_redirect' : '/password_reset_done/'}, name='password_reset'),
     url(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
     #url(r'password_reset/$', auth_views.password_reset,{'email_template_name':'accounts/registration/password_reset_email.html',
         #                                           'subject_template_name':'accounts/registration/password_reset_subject.txt',
       #                                             'post_reset_redirect':'accounts:password_reset_done',
      #                                              'from_email':'accounts@django.com',
      #                                              },name='password_reset'),

    url(r'password_reset_done/$', auth_views.password_reset_done, name='password_reset_done')]
#url(r'^logout/$', auth_views.logout,name='logout'),
#rl(r'^logg/',include('loginex.urls')),
#url(r'^log/',include(loginex.urs)) ]
'''

'''urlpatterns = [
    url(r'^login/', auth_views.login, {'template_name': 'index.html'},name='login'),
    url(r'register/$',views.register, name='register'),
    url('^', include('django.contrib.auth.urls')),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    
'''



urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'index.html'},name='login'),
    url(r'register/$',views.register, name='register'),
    url(r'logout/$',auth_views.logout,{'next_page': '/login'}),
    #url(r'logout/$',auth_views.LogoutView.as_view(template_name='logout.html')),
    url(r'password_change/$',auth_views.PasswordChangeView.as_view(template_name='registration\password_change.html',success_url='/password_change_done')),
    url(r'password_change_done/',auth_views.PasswordChangeDoneView.as_view(template_name='registration\password_change_done.html')),
    url(r'password_reset/$',auth_views.PasswordResetView.as_view(template_name='registration\password_reset_form.html',email_template_name='password_reset_email.html',subject_template_name='registration\password_reset_subject.txt',success_url='/password_reset_done/',from_email='support@yoursite.ma')),
    url(r'password_reset_done/',auth_views.PasswordResetDoneView.as_view(template_name='registration\password_reset_done.html')),
    url(r'password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.PasswordResetConfirmView.as_view(template_name='registration\password_reset_confirm.html',success_url='/password_reset_complete/')),
    url(r'password_reset_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration\password_reset_complete.html')),
    url(r'book/$',views.book_detail,name='book'),
    url(r'^add_book/$',views.add_book,name='AddBook')
]

loginex/home/models.py
from django.db import models

# Create your models here.

loginex/models.py
from django.db import models
import uuid 
import datetime

# Create your models here.
class book(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
	book_name=models.CharField(max_length=25)
	Author_name=models.CharField(max_length=30)
	# date=models.DateField(default=date())
	date = models.DateField(default=datetime.date.today)

	def __str__(self):
		return (self.book_name)

loginex/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import book


class RegistrationForm(UserCreationForm):
    error_css_class='error'
    required_css_class='required'
    

    class Meta:
        model = User
        fields = ('username',
        	'password1',
        	'password2'
        	)

class AddBook(forms.ModelForm):
    """docstring for BookDetail"""
    book_name=forms.CharField(required=True)
    Author_name=forms.CharField(required=True)
    date=forms.DateField()

    class Meta(object):
        model=book
        """docstring for Meta"""
        fields=('book_name','Author_name')
            
        
    

loginex/home/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse

# Create your views here.
def dis(request):
    return HttpResponse("Logged In")

loginex/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import RegistrationForm,AddBook
from django.contrib.auth import authenticate, login
from .models import book
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
import calendar


# Create your views here.
def index(request):
    #return redirect(home.base.html)
    return HttpResponse("Logged In")
	#return render(request,'index.html')
def register(request):
    registered = False
    if request.method == 'POST':
    	user_form = RegistrationForm(request.POST)
    	if user_form.is_valid():
    		#return HttpResponse("HELOOOOOOOOOOOOO")
    		user=user_form.save()
    		#user_form.set_password(user.password)
    		print("HELOOOOOOOOOOOOO")
    		'''username = user_form.get('username')
    		raw_password = user_form.get('password')
    		print(username)
    		user.first_name=user_form.get('first_name')
    		user.last_name=user_form.get('last_name')
    		user.email=user_form.get('email')'''
    		'''user.first_name=request.POST.get('first_name')
    		user.last_name=request.POST.get('last_name')
    		user.email=request.POST.get('email')'''
    		user.save()
    		#login(request, authenticate(username=username, password=raw_password))
    		registered = True
    		print(user_form['username'])

    else:
        user_form = RegistrationForm()
    if registered:
        #return HttpResponse("Logged In")
         #redirect_to = settings.LOGIN_REDIRECT_URL
         return redirect ('/login/')
         #return reverse ('home:base')
    else:
        return render(request, 'register.html', {'user_form': user_form})


@login_required(login_url='/login/')
def book_detail(request):
        book1=book.objects.all();
        print(book1[0].book_name)
        print(book1[0].date.day)
        print(book1[0].date.month)
        print(book1[0].date.year)
        z=calendar.day_name[book1[0].date.weekday()]
        print(z)
        x=book1[0].date.weekday()
        print(x)
        return render(request,'book_detail.html',{'book':book1})


# Final Rendering Template +Using Forms+ Saving Data Into Database
@login_required(login_url='/login/')
def add_book(request):
    registered=False
    if request.method== 'POST':
        add_book_form=AddBook(request.POST)
        print("In If request POST")
        if add_book_form.is_valid():
            registered=True
            add_book=add_book_form.save()
            add_book.save()
        else:
            print("Not Validated")
    else:
        add_book_form=AddBook()
    if registered:
         return redirect('book/')
    else:
        return render(request,'add_book.html',{'add_book':add_book_form})

def author_detail(request):
        auth=book.objects.all();
        return render(request,'author_detail.html',{'book':auth})
    

#def home(request):
  #  return render(request,'index.html')

loginex/templates/add_book.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
	<title>Login Form</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %} ">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css"  href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>

<body>

	

	<!--<form name="AddBook" method="POST" action="">
		{% csrf_token %}
		{{ add_book.as_p }}
		{{ add_book.book_name.id_for_label }}
		{{ add_book.author_name.id_for_label }}
		<button type="submit"> Add Book</button>
	</form>-->





	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" name="AddBook"  method="post">
					 {% csrf_token %}
					 {{ add_book.non_field_errors }}
					<span class="login100-form-title p-b-26">
						Sign Up 
					</span>
					<span class="login100-form-title p-b-48">
						<i class="zmdi zmdi-font"></i>
					</span>
					<div class="wrap-input100" >
						 <input  class="input100" type="text" id="{{add_book.book_name.id_for_label }}" name="book_name" for="{{add_book.book_name.id_for_label }}">
						<span class="focus-input100" data-placeholder="Username"></span> 
					</div>
					{{ add_book.book_name.errors }}


					<div class="wrap-input100" >
						 <input  class="input100" type="text" id="id_Author_name" name="Author_name" for="{{add_book.Author_name.id_for_label }}">
						<span class="focus-input100" data-placeholder="Author Name"></span>
					</div>
					{{ add_book.author_name.errors }}

					<div class="wrap-input100" >
						 <input  class="input100" type="date" id="id_date" name="date" for="{{add_book.date.id_for_label }}">
						<span class="focus-input100" data-placeholder="Date"></span>
					</div>
					{{ add_book.date.errors }}


					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn" type="submit">
								Add Book
							</button>
						</div>
					</div>
		</form>

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src=" {% static 'vendor/jquery/jquery-3.2.1.min.js' %}" ></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %} "></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

loginex/templates/book_detail.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
	<title>Book Detail</title>
</head>

  {% if user.is_authenticated %}
        <p>Welcome {{ user.username }} !!!</p>       
    {% endif %}
<body>
	{% for bb in book%}
		{{bb.book_id}}
		{{bb.book_name}}
		{{bb.date}}
	{% if user.username == "admin" %}
		{{bb.Author_name}}
	<br>
	{% endif %}
	{% endfor %}

	<br>{{user.id}}<br>

	<a href='/add_book/' >Add Book</a>
<form class="login100-form validate-form" name="LoginoutForm"  method="post">
	   {% csrf_token %}
	<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								<a href="logout/">
								Logout
							</a>
							</button>
						</div>
					</div>
</form>
</body>

loginex/templates/index.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
	<title>Login Form</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %} ">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css"  href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>

<body>
	
	
	

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" name="LoginForm"  method="post">
					 {% csrf_token %}
					<span class="login100-form-title p-b-26">
						Welcome
					</span>
					<span class="login100-form-title p-b-48">
						<i class="zmdi zmdi-font"></i>
					</span>

					<div class="wrap-input100" >
						 <input  class="input100" type="text" id="username" name="username" >
						<span class="focus-input100" data-placeholder="Username"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="password" name="password" id="password">
						<span class="focus-input100" data-placeholder="Password"></span>
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Login
							</button>
						</div>
					</div>

					<div class="text-center p-t-115">
						<span class="txt1">
							Don’t have an account?
						</span>

						<a class="txt2" href="/register">
							Sign Up
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src=" {% static 'vendor/jquery/jquery-3.2.1.min.js' %}" ></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %} "></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

loginex/templates/login.html
{% extends "login1.html" %}
{%block content%}
    <div id="login">
        <form class="form-horizontal" name="LoginForm"  method="post" action="">
        {% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}" />
        {% endif %}

        <div class="control-group">
            <label class="control-label" for="{{ username}} ">UUUUsername</label>
            <div class="controls">
                <input type="text" id="username" name="username"  placeholder="Username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="{{ password }} ">Password</label>
            <div class="controls">
                <input type="password" name="password" id="password" placeholder="Password">
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">Login</button>
            </div>
        </div>
        </form>
    </div>
{%endblock%}

loginex/templates/login1.html
<!DOCTYPE html>
{% load static %}
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Sign-Up/Login Form</title>
  <link href="{% static 'CSS/STYLE.CSS' %}" rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  
      <link rel="stylesheet" href="{% static 'CSS/STYLE.CSS' %}">
</head>

<body>

  <div class="form">
      
      <div class="tab-content">
        <div id="signup">   
          <h1>LOG IN  Form</h1>
          
          {%block content%}

          {%endblock%}

        </div>
        
      </div><!-- tab-content 
      
</div> <!-- /form -->
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script  src="js/index.js"></script>
</body>

</html>

<!--<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Sign-Up/Login Form</title>
  <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/CSS'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  
      <link rel="stylesheet" href="CSS/STYLE.CSS">
      <link rel="stylesheet" href="{% static 'CSS/STYLE.CSS' %}">

  
</head>

<body>

  <div class="form">
      
      <ul class="tab-group">
        <li class="tab"><a href="#signup">Sign Up</a></li>
        <li class="tab"><a href="#login">Log In</a></li>
      </ul>
      
      <div class="tab-content">
        <div id="signup">   
          <h1>Sign Up</h1>
          
          <form action="/" method="post">
          
          <div class="top-row">
            <div class="field-wrap">
              <label>
                First Name<span class="req">*</span>
              </label>
              <input type="text" required autocomplete="off" />
            </div>
        
            <div class="field-wrap">
              <label>
                Last Name<span class="req">*</span>
              </label>
              <input type="text"required autocomplete="off"/>
            </div>
          </div>

          <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input type="email"required autocomplete="off"/>
          </div>
          
          <div class="field-wrap">
            <label>
              Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off"/>
          </div>
          
          <button type="submit" class="button button-block"/>Get Started</button>
          
          </form>

        </div>
        
        <div id="login">   
          <h1>Welcome!</h1>
          
          <form action="/" method="post">
          
            <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input type="email"required autocomplete="off"/>
          </div>
          
          <div class="field-wrap">
            <label>
              Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off"/>
          </div>
          
          <p class="forgot">Forgot Password?</p>
          
          <button class="button button-block"/>Log In</button>
          
          </form>

        </div>
        
      </div><!-- tab-content -->
      
</div> <!-- /form -->
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

  

    <script  src="js/index.js"></script>




</body>

</html>